/*  The Numbers In the Sequence:
      0,1,1,2,3,5,8,13,.....are called Fibonacci numbers
    Write A program to calculate and print (N) fibonacci numbers.
    hint: A fibonacci number or term is generated by adding the two previous terms or numbers of the same series i.e, every third term or number is the sum of two previous numbers or terms by taking 0 ,1 as first two terms or numbers.

*/
#include<stdio.h>
int main()
{
    int first=0;
    int second=1;
    int third;
    int n;
    printf("Enter The Value Of n :");
    scanf("%d", &n);
    printf("The Fibonacci series :-\n");
    printf("%d %d ", first , second);
    for (int j = 2; j<=n; j++)  
    {
       third=first+second;
       printf("%d  " , third, "  ");
       first=second;
       second=third;
    }
    return 0;

}